export * from "./Usuario";
export * from "./Avaliacao";
export * from "./Aluno";
export * from "./Professor";
export * from "./Responsavel";
export * from "./Turma";
export * from "./Disciplina";
export * from "./Presenca";
export * from "./Nota";
