export enum CategoriaObservacao {
    FALTA = 'FALTA',
    INDISCIPLINA = 'INDISCIPLINA',
    ATIVIDADE = 'ATIVIDADE',
    DESEMPENHO = 'DESEMPENHO',
    PARTICIPACAO = 'PARTICIPACAO',
    COMPORTAMENTO = 'COMPORTAMENTO',
    SAUDE = 'SAUDE',
    EMOCIONAL = 'EMOCIONAL',
    JUSTIFICATIVA = 'JUSTIFICATIVA',
    REUNIAO = 'REUNIAO',
    OBSERVACAO_GERAL = 'OBSERVACAO_GERAL',
}
