server:
  port: ${PORT}

spring:
  profiles:
    active: dev

  application:
    name: ${HOSTNAME}

  config:
    import: optional:configserver:${CONFIG_URL}

eureka:
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

message: Professor Service is up

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
      path: /
      threshold: 10MB

info:
  app:
    name: ${HOSTNAME}
    version: 1.0.0
    description: Professor Service Application
  svc:
    port: ${PORT}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  packagesToScan: com.diario.professorservice.controller

jwt:
  secret: ${SECRET}