spring:
  application:
    name: aluno-service

eureka:
  instance:
    hostname: aluno-service

message: Aluno Service is up

info:
  app:
    name: aluno-service
    description: Aluno Service Application

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  packagesToScan: com.diario.alunoservice.controller

jwt:
  secret: ${SECRET}
