server:
  port: ${PORT}

spring:
  profiles:
    active: prod

  application:
    name: ${HOSTNAME}

eureka:
  instance:
    hostname: ${HOSTNAME}

message: Aluno Service is up

info:
  app:
    name: ${HOSTNAME}
    description: Aluno Service Application
  svc:
    port: ${PORT}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  packagesToScan: com.diario.alunoservice.controller

jwt:
  secret: ${SECRET}
