server:
  port: ${PORT}

spring:
  application:
    name: ${HOSTNAME}

  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL}
          default-label: main
          clone-on-start: true
          force-pull: true
          search-paths:
            - configs
          timeout: 5

eureka:
  instance:
    hostname: ${HOSTNAME}

message: Config Service is up

info:
  app:
    name: ${HOSTNAME}
    description: Centralized Configuration Service
  svc:
    port: ${PORT}
