spring:
  application:
    name: user-service

eureka:
  instance:
    hostname: user-service

message: User service is up

info:
  app:
    name: user-service
    description: User Service Application

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  packagesToScan: com.diario.userservice.controller
