server:
  port: ${PORT}

spring:
  application:
    name: ${HOSTNAME}

  config:
    import: optional:configserver:${CONFIG_URL}

eureka:
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL}

  server:
    wait-time-in-ms-when-sync-empty: 300000

message: Eureka Service is up

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
      path: /
      threshold: 10MB

info:
  app:
    name: ${HOSTNAME}
    description: Eureka Service Registry
    version: 1.0.0
